### ISSUE TITLE
Update for BandedMatrices.jl v0.4

### ISSUE THREAD

**Issue by dlfivefifty** [wormell/Poltergeist.jl#4]
I've changed some of the internal structure of BandedMatrices.jl, and so this package is now broken:

1. `BLASBandedMatrix` is removed
2. `αΑ_mul_B_plus_βC` is now just `mul!(C, A, B, α, β)` as in Julia v0.7 SparseArrays.jl

**Comment by wormell** [comment]
No issues here as Poltergeist uses only ragged matrices. Cheers!
