### ISSUE TITLE
Tag new version for ApproxFun v0.8

### ISSUE THREAD

**Issue by dlfivefifty** [wormell/Poltergeist.jl#5]
I added an upper bound to METADATA for Poltergeist, as there were a number of changes in ApproxFun 0.8.

(In retrospect, this may have been a mistake: I forgot at the time our conversion before where you said there were no issues. So I could also just revert that METADATA change, though if this is due a new tag that's the easier route.)

**Comment by wormell** [comment]
It looks like 0.8 did break some stuff, which I've fixed, and new version tagged. Cheers!
